apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    # Setting olm.maxOpenShiftVersion automatically
    # This property was added via an automatic process since it was possible to identify that this distribution uses API(s),
    # which will be removed in the k8s version 1.22 and OpenShift version OCP 4.9. Then, it will prevent OCP users to
    # upgrade their cluster to 4.9 before they have installed in their current clusters a version of your operator that
    # is compatible with it. Please, ensure that your project is no longer using these API(s) and that you start to
    # distribute solutions which is compatible with Openshift 4.9.
    # For further information, check the README of this repository.
    olm.properties: '[{"type": "olm.maxOpenShiftVersion", "value": "4.8"}]'
    certified: 'false'
    repository: github.ibm.com/anz-tech-garage/tpn-operator
    alm-examples: |-
      [
        {
          "apiVersion": "tpn.example.com/v1alpha1",
          "kind": "Telstraprogrammablenetwork",
          "metadata": {
            "name": "tpn-sample"
          },
          "spec": {
            "bandwidth": 40
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v0.19.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
    containerImage: 'quay.io/anz-ce/tpn-operator:v1.0.0'
    createdAt: '2020-08-11T12:00:00Z'
    categories: 'Developer Tools'
    description: Operator for the Telstra Programmable Network
    support: Create an issue at github.ibm.com/anz-tech-garage/tpn-operator
  name: tpn-operator.v1.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Telstraprogrammablenetwork is the Schema for the tpn API
      kind: Telstraprogrammablenetwork
      name: tpns.tpn.example.com
      version: v1alpha1
      displayName: Telstra Programmable Network 
  displayName: Telstra Programmable Network
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAH8AAACQCAYAAAAhr7REAAAABmJLR0QA/wD/AP+gvaeTAAAO3klEQVR4nO2de3BU133HP7+7eiBpdyUBAhKcxiRO7MR2bWxSE4jtYiMEBMYeJwhP7LitG5c2k9h10jQepw/cjieeNJmJm2maMG3q2qYF0XjG0BAhJaZxXJJOaWKDH5hAeBgMSKDHrh4I7d5f/xCKhV672r17f3e1+/lrH2fP+Y6+uueee87v/I5QxB/ueTaKSijt8s6MGbhUADCYnEHpxddeIFxgc+P+Es8qzJZ1TWU47l2IczfojcA8IDj6siU5xfJu4p3XIcD1UozsAZYG44/buHUpIf1nVK4EtVZTALivQBCurE9tXY3L91FmWEspHJyXARxTDeuaFuDyb1A03lfU3QfW5of0G0C1qYbCw6Xswn4AMZOwfssHETlgqqEwOciW9VeC5ZXvyCcoGm/BvuEXdua73GrWdiGj8vLwSzvzhYVmbRcywv7hlzbmr2uaD8wxabvQSWJ85ZfoDSbtFulkW+Px4Tc25itF823YN/KN0T1fivd7C0RfHvnWyHy90abdAkfF+Mpf11QHXOZ7u0XAkVcueeu/ALfY5duQoKz3tZEfGHT7TnGwZ4FwkKf+4PzIjwyu/OJI3wS9dLAHFuZr8RnfhksHe+C3+fc8GwXe52ubRYYQ+d/RH/lrfjJ0A8WVPP9Ruoh0/nT0xz53+05xpG/DU2zaMDj6Q7/v+cX7vd8oXTjJx8f7ym/zizN7/pJE5Pf490+dHe9L/8xfu6MS+KBv7RXpQfVetjRun6iAf+ZX9v42Q9sPiuSWQdCtqN7I1ru3TFbQv7j9UMk5XHeDb+2NQa8CHrZrnzMgf5XD+vsRjlNyfi/P3Nebzg8K57FrfdPnEP2WoYIfsGX9GsP2x2Abt+8njvHMoujrpu2PQ+GY77LItH119qcu5C+FYf7aHZUIH7YVkXzVtv2xFIb54f7rsH3SSJIMHTBsf1wKw3xc2y5fOMS2xn5TDeNQGOar2M4sKoEb7EGhmI8YX/kauMEeeDHJs1EdlvZeDclrUbkGuAZYANSC1IJWXizpAh0I53DpwOEMymFEDoP7a5zSV7m98mTWekbz6aerGNSrPK93Sshrqcv4T2bmqwqtvbeBew/EP44yZ/z5oktSrDjAbJTZyIivVAGBZAJ2xU4j/BJ0L07oRfpje1j77r6MNA4zUH49jvG0ckICN9KHqZrfpGXUxO+jNf7nwAc8VyPMA1aBrMJ1oTx8gZbYz1FpRWUHK8OvpKxjTJ2yyDjPzwXa6w5aCpiI9M3f1b0Kif89cEXu5IyhDLgF0VsQ/VtaYkdAtuPoVpZHf5ZWDY7eYOq98ib/tSyRuqD/pDZ/x9uVlIefBD6TezkpWQD6EC4P0RI7BPIMoeRmbq85POEvlI/4qG8sAR3sQarR/u6eeZRXvUQwjB/NFaCPkXQO0hJvZldsLU166b19XVMY6xgCCeb9HiYzf2ffZQy6/50Hmyod0AaE7dTED9MS+yLPt0cACCUXYh1DoMEc6cNE5rd2VFOS2En+hVm/F/g6FeXHaIk9zszILdaCSJJH3f5GdXBD/wFc678cz6gFHmVmzW3GOnq5+vVjxhomZKz5S3s2ILLcQIv3nGh7j7GC19i40dOsuV5yqfnNve9C9atGWjxGj3F+8P2mEoTA3u9htPmS/ALTJSNm78BRrNcu3OCO9GHkH2d3Zw3CA4ZavKWtq8daArh5Yn7CuZfpctUDnGirTF0ox7hOnnT7yp2GOrxGOd72W8YaOtjW6P0qpYcMmb+7swbE/pnYO44wMGg9RxHIAI6RDJk/6CwBSm2leEhP31uY70kI7pz+MEPmyzTbOt3WbT/YC2Co9miGzFfrSBePOXYmbC0BJ1+6fdV5xjq8xOVk+3utRZAI7pz+MBe7fWYb6/AOV49wIXG5sYpTbGvsMNaQkouPelM47C/o9J4PwkJKoCd3hpl+odunO4KwOSKfzNdAxphlxPG2iLWEoIZqj+biPV+6jHV4hcvb7Zdbi8AJ/mAP3hnttxvr8AZXDzGYtJ7WVXrK3zDWkBbDA76jpiq8It7/lrUE4Cjb74hbi0iHi1e+BGGEnD1nzg1YSyBSdchaQroMd/t5cY9KybEADPYWf6ialviTqAY+39GQ+QMDL5P/Z5cnOXXWNmwLoCY8A/RBWuNPs1cDvVg2ZP4ddXHy5Nl0Qlz9FQn33dYyqCqfe/HVvXTGn2PH2/ZBJRMwcpKn1UyFF/T0n7CWQFlJEseZ+5v3yhpmhJvZeS5qqGpC3jFftMVQR/acar9gLYFZ0bfHfKbcTEnpD2ntCFyI3DvmV0VfBM5PXDTgHGu3v7rm1p6b4JslaMmuoP0DvGP+EukHGZOQP09IcLrDz63j4zN35mS9z01oyY+GQuaCwai4fd1mpCM73OSbJJL2MQk14YoUJRaRKPlxUHqAUat6iSbysevv7jtlLQGAyvLU/4CqN6AlPwjCU8Cl5tfP7Eb0eSMtmXO6y36wV16aQKQuzdJLKY88R5OW5VRTCsau5ytPG+jIjuOn7e+js6unGKOvDdTEN49JKOEjY80vjbYAwehG0+MCpzq8Tw41VebVZBK29Ulq45uspoLHmr9MEqh820BLZrjuQVw33e42d8yuzSwgRrmflvgjHqtJi/HDuMr0O0AQwqFS090bjF6qtirzAZzwOLu67/FQTVqMb/6y6FmUZ33Wkhmnzo05L86EihnvyuLXgsj3aI3/rldy0mHiAM6QfJN8WOk7cmamtQRmlA0ikq2OMlSbaO72bbJqYvOXR14HdvglJEMGaO+yH+zVVXsVQVSHIzv8WgiaPHRb5SsMJUwOJgn3TVx3lrUM5tR4GQB7FaHS7/nxBDC5+Q2RV4HNuRaRMd3x09YSAJiT4Uh/IoRP8KP4Fz2tcxxSb9oIuY8BwRhUjebk2aS1BABqw96HjylP0Bxf5nm9I0ht/u01h1H9p1yKyJgT7fZdPkB5WS4iiEI4upXm3myeIiYlve1aSeevgaBtPOynrdt+sFdZfgGRXK3S1eG4T+Xq/p+e+asj7Yj8RS4EZEwi+SauW2stg7qaHIeP6QpaYw/moub0N2p2hjeB/F8uRGREV98ZawkAzKntzH0j8gTN8au9rjV98xslibifIygTPyfbg6FjTo0fj8IzcNxnvV4CntoW7frqnwObvBSQMW8FYGYPoLrKp40icj21sb/0ssap78/vH/gScNRLEVNH+mjvDkYeofLS+b61pfIlWuMf8qq6qZt/R10clT/EsvtPJA6gah+tG67oR8TPLWLloN/1avSfWWaOhsgLIP/ghYCM6OhpM2t7JLOr/d8ootxMS/x+L6rKPC2L9j4C/MoLEVPmVFswNkHOre02aVf4GjvjWQewZG5+w7xeXPduwP9t0cfag5E9rM6Xkf54zKTE/ZtsK8kuIdPKml+g8oVsRUyRHs7GrvS5zfGJVhome5TPsCuW1aA3+2xcDZFvgzZlXU+6DCbfALXPsCkC5WWWyR5LcMjqVBRvUrElEg8A/mSk6IwFY41hXu0RhCpTDcqdtMY+lunPvTF/9awY4twF5H4AdCIguaOufX8wYgmUv8v00c+7JIz14f3AfUBu19iPt83Jaf3pUFHexfzZ11jLuMhiWmOrMvmhtxk4V0S3I+Ry9S9GV9x+sLd68esI9vl/foM8msmvvE+/Wh99ApHchH4NJg/gYrfBUVDqb/wJ1ZVLzDSMz9JMwr5zk3u3M3w/8ILn9Z7rthvszQwfoPG2vbxnzq1mGiZDmfKun9zNlLV2VKMlP8XLY1nPdTdz+FTqY9+9IOQMUF4aojbsMm/mXEKhhQQ7UbWCXsmK6rRnXXM7Tbqz7zJKEi8xdMBxkZwjT7Ii8qdpl86lFACau6/AkT2A/WbK6U8X2ncZDfN60ymc+25sZfUhXHclfswBFKmBirTPR/TnHray5he4uoLiP4APyL1pl8yljDHsii3BoRkN0jPytCOBynwaIiljHvwdvTZE9+DKGiCte1KRjChBuCudgv4/ujREXkRZAUyX0z0CiKY13WsXEdPauxBNNgP2c/XTjx66IrNolEmzlNlNWtRX/RLlVsA+YfL0I0y0Z2mqQrYzVg3RAySTN2MVCzidETflNLT9dOWq2qOUsgT4H2sp0wqRRamK2JsPQwmgBnpuI/hpYPKJlOYHIwR6mCYNUR3/R4QHrKVMC1ydxcrqCVdCg3HlD9MoSRqif4TyKEHOBZQvlDDpmUPBMn+YhuhXUe4EYtZS8pqkk4fmAzREdyCyGDhoLSVvESZNWxNc8wHqI29QmrwJ+KG1lLxEdNI1lGCbD7CstouuyFpUHyPXkcHTDWXSnczBNx8uDgSrN+JKPTDFvPYFjGpAp3czYWVkNwlZCOy0lpIfyKSrp/llPgxlBquPrAH+DIsdwnmFTBo8k3/mA4goK6LfQGURsNdaTmAJya8n+zo/zR+mIfIqpZGPAl+h2AuMJSGvTfZ1sKZ3s2FX/BpE/4U05rQLhDOsiE561Ft+X/kjGe4FRB+mGCUEKj9OVWT6mA9Dh0PVV38TN/Rh4BmCkjDSBDflE9H06fbHozX2MVS/BXK9tRR/kT5KE/NZVjtpDzi9rvzR1EdfojT6EVQ2UEiTQ6qbUxkP0/3KH8keraAn/nngEcA+W3fuUBznepaH96UqWDjmD7O7s4YLoS8j8iCo+WHGOeBfWRH9/XQKFp75w+yKz0H0IeCzgP1ZvN7QQ6nzAZaF08oXVLjmD/N8e4TK8g0oDwO5OC7FR+RPWBH5Ttqlcyklr2jSMqrjn0b4PHCdtZwpI2yiPrphaj8pMpbW7sWo/DHQCFRYy0mBInyd5ZEvIzKleY2i+ZPxn121lMl9IA8Anh9z4gExRO6nPvL9TH5cND9dmnuuw3HXA3cDC6zlgLQQSn6W22sOZ1yDl3IKAlWhJfY7IJ9EWAP4feLHG4hspD6Sdb7jovnZ0tx9BcJqxPk46M3kZozgovoCON/lZ+Hn2Cie7Gkomu8le7WUs7GFhLgJdT4KupjMbxG9wE8QbYXkc9TPPO6hUqBofu7ZoxX09Swgqe/D0ctRuRyYBVQBISAJmgTnDKonETlKUvcRjxyiUXIarfz/234V5o+5vvQAAAAASUVORK5CYII=
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apps
          resources:
          - deployments/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - list
        - apiGroups:
          - tpn.example.com
          resources:
          - tpns
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - tpn.example.com
          resources:
          - tpns/status
          verbs:
          - get
          - patch
          - update
        serviceAccountName: tpn-operator-manager-role
      - rules:
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: tpn-operator-proxy-role
      - rules:
        - nonResourceURLs:
          - /metrics
          verbs:
          - get
        serviceAccountName: tpn-operator-metrics-reader
      - rules:
        - verbs:
          - '*'
          apiGroups:
            - '*'
          resources:
            - '*'
        - verbs:
          - '*'
          nonResourceURLs:
            - '*'
        serviceAccountName: default
      deployments:
      - name: tpn-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                command:
                - /manager
                image: quay.io/anz-ce/tpn-operator:v1.0.0
                name: manager
                resources:
                  limits:
                    cpu: 100m
                    memory: 30Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: tpn-operator-leader-election-role
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ide
  - ai
  - ml
  links:
  - name: Telstra Programmale Network Operator
    url: https://www.telstra.com.au/business-enterprise/products/networks/sdn/telstra-programmable-network
  maturity: alpha
  maintainers:
    - name: Jo Doe
      email: jodoe@telstra.com
  provider:
    name: Jo Doe
  description: >
    Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services.:

      [Telstra Programmable Network API] (https://dev.telstra.com/content/programmable-network-api)


    **Prerequisites:**

    - Cluster administrator privileges


    **Installation:**


    1. Install the operator through the catalog.

    2. Select Telstra Programmable Network under "Installed Operators"

    3. Create an instance of  using the default configuration "tpn-sample"

  version: 1.0.0
